---

- name: create daily sync plan
  katello_sync_plan:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    name: "daily"
    interval: "daily"
    enabled: true
    sync_date: "2019-01-01 00:00:00 UTC"
  delegate_to: "{{ delegate_host }}"
