---

- name: create daily sync plan
  theforeman.foreman.katello_sync_plan:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.name }}"
    name: "daily"
    interval: "daily"
    enabled: true
    sync_date: "2020-01-01 00:00:00 UTC"
  delegate_to: "{{ delegate_host }}"
