---

- name: "publish content view version {{ content_view }} to the library"
  katello_content_view_version:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    content_view: "{{ content_view }}"
    lifecycle_environments:
      - Library
  delegate_to: localhost
