---

- name: sync all repos
  block:

    - name: kick off repository Sync tasks
      katello_sync:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_initial_organization }}"
        product: "{{ product.1.product }}"
      loop_control:
        loop_var: product
      loop: "{{ content_views | subelements('repos') }}"
      async: 999999
      poll: 0
      register: repos_sync
  delegate_to: "{{ delegate_host }}"

- name: wait for repos to finish syncing
  shell: hammer --csv task list --search "state = running and action ~ Synchronize" | wc -l
  register: repo_sync_status
  until: repo_sync_status | int > 1
  retries: 960
  delay: 60
