---

- name: sync all repos
  block:

    - name: kick off repository Sync tasks
      katello_sync:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_initial_organization }}"
        product: "{{ product.1.product }}"
      loop_control:
        loop_var: product
      loop: "{{ content_views | subelements('repos') }}"
      async: 999999
      poll: 0
      register: repos_sync


    - debug:
        msg: "{{ item }}"
      loop: "{{ repos_sync.result }}"

    - name: wait for repos to finish sncing
      async_status:
        jid: "{{ repo_sync.ansible_job_id }}"
      when: repo_sync.ansible_job_id is defined
      loop_control:
        loop_var: repo_sync
      with_items:
        - "{{ repos_sync }}"
      register: async_job_result
      until: async_job_result.finished
      retries: 999
      delay: 10
  delegate_to: "{{ delegate_host }}"
