---

- name: upload manifest to satellite
  katello_manifest:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    state: present
    manifest_path: "{{ satellite_manifest_path }}"
  delegate_to: localhost
