---

- name: create content view cv-server-rhel7
  theforeman.foreman.katello_content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organiztion.name }}"
    name: cv-server-rhel7
    repositories:
      - name: Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
        product: Red Hat Enterprise Linux Server
      - name: Red Hat Satellite Tools 6.6 for RHEL 7 Server RPMs x86_64
        product: Red Hat Enterprise Linux Server
  delegate_to: localhost
  register: publish_content_view

- name: publish new version of cv-server-rhel7
  include_tasks: /home/jswanson/satellite6.6-dev-rearchitect/roles/satellite/tasks/publish-content-view.yml
  vars:
    content_view: cv-server-rhel7
  when:
    - publish_content_view is defined
    - publish_content_view.changed

