---

- name: create content view task file directory
  file:
    path: "{{ role_path }}/tasks/{{ organization.name }}/content-views"
    state: directory
  delegate_to: "{{ delegate_host }}"

- name: push task file to create composite content view
  template:
    src: templates/create-composite-content-view.yml.j2
    dest: "{{ role_path }}/tasks/{{ organization.name }}/content-views/{{ composite_content_view.name }}.yml"
  loop_control:
    loop_var: composite_content_view
  loop: "{{ organization.composite_content_views }}"
  delegate_to: "{{ delegate_host }}"

- name: include tasks to create composite content views
  include_tasks: "{{ role_path }}/tasks/{{ organization.name }}/content-views/{{ composite_content_view.name }}.yml"
  loop_control:
    loop_var: composite_content_view
  loop: "{{ organization.composite_content_views }}"
