---

- name: "setup {{ delegate_host }} to use foreman ansible modules"
  block:
#    - name: install pip from epel
#      yum:
#        name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-pip-8.1.2-10.el7.noarch.rpm
#        state: present
#      when:
#        - im_ok_with_pip_from_epel
#    - name: fail if im_ok_with_pip_from_epel is false
#      fail:
#        msg: "im_ok_with_pip_from_epel is set to false and SCL pip code is not ready."
#      when:
#        - not im_ok_with_pip_from_epel
    - name: install apypie via pip
      pip:
        name: apypie
        state: present
        executable: pip3
        become: true
  delegate_to: "{{ delegate_host }}"
