---

- name: create content credentials for custom products
  theforeman.foreman.katello_content_credential:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.name }}"
    name: "{{ content_credential.1.content_credential_name }}"
    content_type: gpg_key
    content: "{{ lookup('url', content_credential.1.content_credential) }}"
  when:
    - content_credential.1.content_credential is defined
  loop_control:
    loop_var: content_credential
  loop: "{{ organization.content_views | subelements('repos') }}"
  delegate_to: "{{ delegate_host }}"
